apiVersion: v1
kind: Service
metadata:
  name: sample-project-service
spec:
  selector:
    app: sample-project-pod
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 80
  type: LoadBalancer